---
- name: Generate rabbitmq_root_password
  set_fact:
    bx_transformer_rabbitmq_root_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=20') }}"
  when: bx_transformer_rabbitmq_root_password is not defined
  no_log: true

- name: Generate rabbitmq_password
  set_fact:
    bx_transformer_rabbitmq_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=20') }}"
  when: bx_transformer_rabbitmq_password is not defined
  no_log: true
